// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistencia;

#nullable disable

namespace Persistencia.Migrations
{
    [DbContext(typeof(DinoShopContext))]
    [Migration("20230802125957_InitialMigrationCreate")]
    partial class InitialMigrationCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Dominio.Entities.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("int")
                        .HasColumnName("idMarca");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("idDescipcion");

                    b.HasKey("Id");

                    b.ToTable("Marca", (string)null);
                });

            modelBuilder.Entity("Dominio.Entities.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("int")
                        .HasColumnName("idPais");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("nombrePais");

                    b.HasKey("Id");

                    b.ToTable("Pais", (string)null);
                });

            modelBuilder.Entity("Dominio.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("int")
                        .HasColumnName("idPersona");

                    b.Property<string>("ApellidoPersona")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("apellidoPersona");

                    b.Property<int>("EdadPersona")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("edadPersona");

                    b.Property<int>("IdProv")
                        .HasMaxLength(12)
                        .HasColumnType("int")
                        .HasColumnName("idProv");

                    b.Property<int>("IdTipoPer")
                        .HasMaxLength(12)
                        .HasColumnType("int")
                        .HasColumnName("idTipPer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("nombrePersona");

                    b.HasKey("Id");

                    b.HasIndex("IdProv");

                    b.HasIndex("IdTipoPer");

                    b.ToTable("Persona", (string)null);
                });

            modelBuilder.Entity("Dominio.Entities.PersonaProducto", b =>
                {
                    b.Property<int>("IdPersona")
                        .HasMaxLength(12)
                        .HasColumnType("int")
                        .HasColumnName("idPersona");

                    b.Property<int>("IdProducto")
                        .HasMaxLength(12)
                        .HasColumnType("int")
                        .HasColumnName("idProducto");

                    b.HasKey("IdPersona", "IdProducto");

                    b.HasIndex("IdProducto");

                    b.ToTable("ProductoPersona", (string)null);
                });

            modelBuilder.Entity("Dominio.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("int")
                        .HasColumnName("idProducto");

                    b.Property<string>("DatoProducto")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("DescipcionProducto");

                    b.Property<int>("IdMarca")
                        .HasMaxLength(12)
                        .HasColumnType("int")
                        .HasColumnName("IdMarca");

                    b.Property<int>("PrecioProducto")
                        .HasColumnType("int");

                    b.Property<string>("RefProducto")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdMarca");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("Dominio.Entities.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("int")
                        .HasColumnName("idProvincia");

                    b.Property<int>("IdRegion")
                        .HasMaxLength(12)
                        .HasColumnType("int")
                        .HasColumnName("idRegion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("nombreProvincia");

                    b.HasKey("Id");

                    b.HasIndex("IdRegion");

                    b.ToTable("Provincia", (string)null);
                });

            modelBuilder.Entity("Dominio.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("int")
                        .HasColumnName("idRegion");

                    b.Property<int>("IdPais")
                        .HasMaxLength(12)
                        .HasColumnType("int")
                        .HasColumnName("idPais");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("nombreRegion");

                    b.HasKey("Id");

                    b.HasIndex("IdPais");

                    b.ToTable("Region", (string)null);
                });

            modelBuilder.Entity("Dominio.Entities.TipoPersona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("int")
                        .HasColumnName("idTIpoPersona");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("desciptionTIpoPersona");

                    b.HasKey("Id");

                    b.ToTable("TipoPersona", (string)null);
                });

            modelBuilder.Entity("Dominio.Entities.Persona", b =>
                {
                    b.HasOne("Dominio.Entities.Provincia", "Provincia")
                        .WithMany("Personas")
                        .HasForeignKey("IdProv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.TipoPersona", "TipoPersona")
                        .WithMany("Personas")
                        .HasForeignKey("IdTipoPer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");

                    b.Navigation("TipoPersona");
                });

            modelBuilder.Entity("Dominio.Entities.PersonaProducto", b =>
                {
                    b.HasOne("Dominio.Entities.Persona", "Persona")
                        .WithMany("PersonaProductos")
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Producto", "Producto")
                        .WithMany("PersonaProductos")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Dominio.Entities.Producto", b =>
                {
                    b.HasOne("Dominio.Entities.Marca", "Marca")
                        .WithMany("Productos")
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Dominio.Entities.Provincia", b =>
                {
                    b.HasOne("Dominio.Entities.Region", "Region")
                        .WithMany("Provincias")
                        .HasForeignKey("IdRegion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Dominio.Entities.Region", b =>
                {
                    b.HasOne("Dominio.Entities.Pais", "Pais")
                        .WithMany("Regiones")
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Dominio.Entities.Marca", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Dominio.Entities.Pais", b =>
                {
                    b.Navigation("Regiones");
                });

            modelBuilder.Entity("Dominio.Entities.Persona", b =>
                {
                    b.Navigation("PersonaProductos");
                });

            modelBuilder.Entity("Dominio.Entities.Producto", b =>
                {
                    b.Navigation("PersonaProductos");
                });

            modelBuilder.Entity("Dominio.Entities.Provincia", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("Dominio.Entities.Region", b =>
                {
                    b.Navigation("Provincias");
                });

            modelBuilder.Entity("Dominio.Entities.TipoPersona", b =>
                {
                    b.Navigation("Personas");
                });
#pragma warning restore 612, 618
        }
    }
}
